/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as SqlInterviewQuestionsRouteImport } from './routes/sql-interview-questions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PythonCodingPracticeRouteImport } from './routes/python-coding-practice'
import { Route as PythonRouteImport } from './routes/python'
import { Route as PysparkPracticeRouteImport } from './routes/pyspark-practice'
import { Route as PysparkRouteImport } from './routes/pyspark'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as JavaRouteImport } from './routes/java'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as GcpDataEngineerInterviewRouteImport } from './routes/gcp-data-engineer-interview'
import { Route as GcpRouteImport } from './routes/gcp'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as EngineRouteImport } from './routes/engine'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicSlugRouteImport } from './routes/topic.$slug'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const SqlInterviewQuestionsRoute = SqlInterviewQuestionsRouteImport.update({
  id: '/sql-interview-questions',
  path: '/sql-interview-questions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PythonCodingPracticeRoute = PythonCodingPracticeRouteImport.update({
  id: '/python-coding-practice',
  path: '/python-coding-practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PythonRoute = PythonRouteImport.update({
  id: '/python',
  path: '/python',
  getParentRoute: () => rootRouteImport,
} as any)
const PysparkPracticeRoute = PysparkPracticeRouteImport.update({
  id: '/pyspark-practice',
  path: '/pyspark-practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PysparkRoute = PysparkRouteImport.update({
  id: '/pyspark',
  path: '/pyspark',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const JavaRoute = JavaRouteImport.update({
  id: '/java',
  path: '/java',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const GcpDataEngineerInterviewRoute =
  GcpDataEngineerInterviewRouteImport.update({
    id: '/gcp-data-engineer-interview',
    path: '/gcp-data-engineer-interview',
    getParentRoute: () => rootRouteImport,
  } as any)
const GcpRoute = GcpRouteImport.update({
  id: '/gcp',
  path: '/gcp',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineRoute = EngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicSlugRoute = TopicSlugRouteImport.update({
  id: '/topic/$slug',
  path: '/topic/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/engine': typeof EngineRoute
  '/feedback': typeof FeedbackRoute
  '/gcp': typeof GcpRoute
  '/gcp-data-engineer-interview': typeof GcpDataEngineerInterviewRoute
  '/interview': typeof InterviewRoute
  '/java': typeof JavaRoute
  '/practice': typeof PracticeRoute
  '/pyspark': typeof PysparkRoute
  '/pyspark-practice': typeof PysparkPracticeRoute
  '/python': typeof PythonRoute
  '/python-coding-practice': typeof PythonCodingPracticeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sql-interview-questions': typeof SqlInterviewQuestionsRoute
  '/tutorial': typeof TutorialRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/engine': typeof EngineRoute
  '/feedback': typeof FeedbackRoute
  '/gcp': typeof GcpRoute
  '/gcp-data-engineer-interview': typeof GcpDataEngineerInterviewRoute
  '/interview': typeof InterviewRoute
  '/java': typeof JavaRoute
  '/practice': typeof PracticeRoute
  '/pyspark': typeof PysparkRoute
  '/pyspark-practice': typeof PysparkPracticeRoute
  '/python': typeof PythonRoute
  '/python-coding-practice': typeof PythonCodingPracticeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sql-interview-questions': typeof SqlInterviewQuestionsRoute
  '/tutorial': typeof TutorialRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/engine': typeof EngineRoute
  '/feedback': typeof FeedbackRoute
  '/gcp': typeof GcpRoute
  '/gcp-data-engineer-interview': typeof GcpDataEngineerInterviewRoute
  '/interview': typeof InterviewRoute
  '/java': typeof JavaRoute
  '/practice': typeof PracticeRoute
  '/pyspark': typeof PysparkRoute
  '/pyspark-practice': typeof PysparkPracticeRoute
  '/python': typeof PythonRoute
  '/python-coding-practice': typeof PythonCodingPracticeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sql-interview-questions': typeof SqlInterviewQuestionsRoute
  '/tutorial': typeof TutorialRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/engine'
    | '/feedback'
    | '/gcp'
    | '/gcp-data-engineer-interview'
    | '/interview'
    | '/java'
    | '/practice'
    | '/pyspark'
    | '/pyspark-practice'
    | '/python'
    | '/python-coding-practice'
    | '/reset-password'
    | '/sitemap.xml'
    | '/sql-interview-questions'
    | '/tutorial'
    | '/topic/$slug'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/engine'
    | '/feedback'
    | '/gcp'
    | '/gcp-data-engineer-interview'
    | '/interview'
    | '/java'
    | '/practice'
    | '/pyspark'
    | '/pyspark-practice'
    | '/python'
    | '/python-coding-practice'
    | '/reset-password'
    | '/sitemap.xml'
    | '/sql-interview-questions'
    | '/tutorial'
    | '/topic/$slug'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/chat'
    | '/engine'
    | '/feedback'
    | '/gcp'
    | '/gcp-data-engineer-interview'
    | '/interview'
    | '/java'
    | '/practice'
    | '/pyspark'
    | '/pyspark-practice'
    | '/python'
    | '/python-coding-practice'
    | '/reset-password'
    | '/sitemap.xml'
    | '/sql-interview-questions'
    | '/tutorial'
    | '/topic/$slug'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  EngineRoute: typeof EngineRoute
  FeedbackRoute: typeof FeedbackRoute
  GcpRoute: typeof GcpRoute
  GcpDataEngineerInterviewRoute: typeof GcpDataEngineerInterviewRoute
  InterviewRoute: typeof InterviewRoute
  JavaRoute: typeof JavaRoute
  PracticeRoute: typeof PracticeRoute
  PysparkRoute: typeof PysparkRoute
  PysparkPracticeRoute: typeof PysparkPracticeRoute
  PythonRoute: typeof PythonRoute
  PythonCodingPracticeRoute: typeof PythonCodingPracticeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SqlInterviewQuestionsRoute: typeof SqlInterviewQuestionsRoute
  TutorialRoute: typeof TutorialRoute
  TopicSlugRoute: typeof TopicSlugRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sql-interview-questions': {
      id: '/sql-interview-questions'
      path: '/sql-interview-questions'
      fullPath: '/sql-interview-questions'
      preLoaderRoute: typeof SqlInterviewQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/python-coding-practice': {
      id: '/python-coding-practice'
      path: '/python-coding-practice'
      fullPath: '/python-coding-practice'
      preLoaderRoute: typeof PythonCodingPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/python': {
      id: '/python'
      path: '/python'
      fullPath: '/python'
      preLoaderRoute: typeof PythonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pyspark-practice': {
      id: '/pyspark-practice'
      path: '/pyspark-practice'
      fullPath: '/pyspark-practice'
      preLoaderRoute: typeof PysparkPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pyspark': {
      id: '/pyspark'
      path: '/pyspark'
      fullPath: '/pyspark'
      preLoaderRoute: typeof PysparkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/java': {
      id: '/java'
      path: '/java'
      fullPath: '/java'
      preLoaderRoute: typeof JavaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gcp-data-engineer-interview': {
      id: '/gcp-data-engineer-interview'
      path: '/gcp-data-engineer-interview'
      fullPath: '/gcp-data-engineer-interview'
      preLoaderRoute: typeof GcpDataEngineerInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gcp': {
      id: '/gcp'
      path: '/gcp'
      fullPath: '/gcp'
      preLoaderRoute: typeof GcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine': {
      id: '/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof EngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/$slug': {
      id: '/topic/$slug'
      path: '/topic/$slug'
      fullPath: '/topic/$slug'
      preLoaderRoute: typeof TopicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  EngineRoute: EngineRoute,
  FeedbackRoute: FeedbackRoute,
  GcpRoute: GcpRoute,
  GcpDataEngineerInterviewRoute: GcpDataEngineerInterviewRoute,
  InterviewRoute: InterviewRoute,
  JavaRoute: JavaRoute,
  PracticeRoute: PracticeRoute,
  PysparkRoute: PysparkRoute,
  PysparkPracticeRoute: PysparkPracticeRoute,
  PythonRoute: PythonRoute,
  PythonCodingPracticeRoute: PythonCodingPracticeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SqlInterviewQuestionsRoute: SqlInterviewQuestionsRoute,
  TutorialRoute: TutorialRoute,
  TopicSlugRoute: TopicSlugRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
