/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PythonRouteImport } from './routes/python'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as GcpRouteImport } from './routes/gcp'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as EngineRouteImport } from './routes/engine'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicSlugRouteImport } from './routes/topic.$slug'
import { Route as ApiPublicHooksFeedbackEmailRouteImport } from './routes/api/public/hooks/feedback-email'

const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PythonRoute = PythonRouteImport.update({
  id: '/python',
  path: '/python',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const GcpRoute = GcpRouteImport.update({
  id: '/gcp',
  path: '/gcp',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineRoute = EngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicSlugRoute = TopicSlugRouteImport.update({
  id: '/topic/$slug',
  path: '/topic/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksFeedbackEmailRoute =
  ApiPublicHooksFeedbackEmailRouteImport.update({
    id: '/api/public/hooks/feedback-email',
    path: '/api/public/hooks/feedback-email',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/engine': typeof EngineRoute
  '/feedback': typeof FeedbackRoute
  '/gcp': typeof GcpRoute
  '/practice': typeof PracticeRoute
  '/python': typeof PythonRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tutorial': typeof TutorialRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/api/public/hooks/feedback-email': typeof ApiPublicHooksFeedbackEmailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/engine': typeof EngineRoute
  '/feedback': typeof FeedbackRoute
  '/gcp': typeof GcpRoute
  '/practice': typeof PracticeRoute
  '/python': typeof PythonRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tutorial': typeof TutorialRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/api/public/hooks/feedback-email': typeof ApiPublicHooksFeedbackEmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/engine': typeof EngineRoute
  '/feedback': typeof FeedbackRoute
  '/gcp': typeof GcpRoute
  '/practice': typeof PracticeRoute
  '/python': typeof PythonRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tutorial': typeof TutorialRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/api/public/hooks/feedback-email': typeof ApiPublicHooksFeedbackEmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/engine'
    | '/feedback'
    | '/gcp'
    | '/practice'
    | '/python'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tutorial'
    | '/topic/$slug'
    | '/api/public/hooks/feedback-email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/engine'
    | '/feedback'
    | '/gcp'
    | '/practice'
    | '/python'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tutorial'
    | '/topic/$slug'
    | '/api/public/hooks/feedback-email'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/chat'
    | '/engine'
    | '/feedback'
    | '/gcp'
    | '/practice'
    | '/python'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tutorial'
    | '/topic/$slug'
    | '/api/public/hooks/feedback-email'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  EngineRoute: typeof EngineRoute
  FeedbackRoute: typeof FeedbackRoute
  GcpRoute: typeof GcpRoute
  PracticeRoute: typeof PracticeRoute
  PythonRoute: typeof PythonRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TutorialRoute: typeof TutorialRoute
  TopicSlugRoute: typeof TopicSlugRoute
  ApiPublicHooksFeedbackEmailRoute: typeof ApiPublicHooksFeedbackEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/python': {
      id: '/python'
      path: '/python'
      fullPath: '/python'
      preLoaderRoute: typeof PythonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gcp': {
      id: '/gcp'
      path: '/gcp'
      fullPath: '/gcp'
      preLoaderRoute: typeof GcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine': {
      id: '/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof EngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/$slug': {
      id: '/topic/$slug'
      path: '/topic/$slug'
      fullPath: '/topic/$slug'
      preLoaderRoute: typeof TopicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/feedback-email': {
      id: '/api/public/hooks/feedback-email'
      path: '/api/public/hooks/feedback-email'
      fullPath: '/api/public/hooks/feedback-email'
      preLoaderRoute: typeof ApiPublicHooksFeedbackEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  EngineRoute: EngineRoute,
  FeedbackRoute: FeedbackRoute,
  GcpRoute: GcpRoute,
  PracticeRoute: PracticeRoute,
  PythonRoute: PythonRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TutorialRoute: TutorialRoute,
  TopicSlugRoute: TopicSlugRoute,
  ApiPublicHooksFeedbackEmailRoute: ApiPublicHooksFeedbackEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
