/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SqlInterviewQuestionsRouteImport } from './routes/sql-interview-questions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PythonTutorialRouteImport } from './routes/python-tutorial'
import { Route as PythonCodingPracticeRouteImport } from './routes/python-coding-practice'
import { Route as PythonRouteImport } from './routes/python'
import { Route as PysparkPracticeRouteImport } from './routes/pyspark-practice'
import { Route as PysparkRouteImport } from './routes/pyspark'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as JavaTutorialRouteImport } from './routes/java-tutorial'
import { Route as JavaRouteImport } from './routes/java'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as GcpDataEngineerInterviewRouteImport } from './routes/gcp-data-engineer-interview'
import { Route as GcpRouteImport } from './routes/gcp'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EngineRouteImport } from './routes/engine'
import { Route as CppRouteImport } from './routes/cpp'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CCppCodingPracticeRouteImport } from './routes/c-cpp-coding-practice'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicSlugRouteImport } from './routes/topic.$slug'
import { Route as PythonTutorialTopicIdRouteImport } from './routes/python-tutorial.$topicId'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SqlInterviewQuestionsRoute = SqlInterviewQuestionsRouteImport.update({
  id: '/sql-interview-questions',
  path: '/sql-interview-questions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PythonTutorialRoute = PythonTutorialRouteImport.update({
  id: '/python-tutorial',
  path: '/python-tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const PythonCodingPracticeRoute = PythonCodingPracticeRouteImport.update({
  id: '/python-coding-practice',
  path: '/python-coding-practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PythonRoute = PythonRouteImport.update({
  id: '/python',
  path: '/python',
  getParentRoute: () => rootRouteImport,
} as any)
const PysparkPracticeRoute = PysparkPracticeRouteImport.update({
  id: '/pyspark-practice',
  path: '/pyspark-practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PysparkRoute = PysparkRouteImport.update({
  id: '/pyspark',
  path: '/pyspark',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const JavaTutorialRoute = JavaTutorialRouteImport.update({
  id: '/java-tutorial',
  path: '/java-tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const JavaRoute = JavaRouteImport.update({
  id: '/java',
  path: '/java',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const GcpDataEngineerInterviewRoute =
  GcpDataEngineerInterviewRouteImport.update({
    id: '/gcp-data-engineer-interview',
    path: '/gcp-data-engineer-interview',
    getParentRoute: () => rootRouteImport,
  } as any)
const GcpRoute = GcpRouteImport.update({
  id: '/gcp',
  path: '/gcp',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineRoute = EngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const CppRoute = CppRouteImport.update({
  id: '/cpp',
  path: '/cpp',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CCppCodingPracticeRoute = CCppCodingPracticeRouteImport.update({
  id: '/c-cpp-coding-practice',
  path: '/c-cpp-coding-practice',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicSlugRoute = TopicSlugRouteImport.update({
  id: '/topic/$slug',
  path: '/topic/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PythonTutorialTopicIdRoute = PythonTutorialTopicIdRouteImport.update({
  id: '/$topicId',
  path: '/$topicId',
  getParentRoute: () => PythonTutorialRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/c-cpp-coding-practice': typeof CCppCodingPracticeRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/cpp': typeof CppRoute
  '/engine': typeof EngineRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/gcp': typeof GcpRoute
  '/gcp-data-engineer-interview': typeof GcpDataEngineerInterviewRoute
  '/interview': typeof InterviewRoute
  '/java': typeof JavaRoute
  '/java-tutorial': typeof JavaTutorialRoute
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/pyspark': typeof PysparkRoute
  '/pyspark-practice': typeof PysparkPracticeRoute
  '/python': typeof PythonRoute
  '/python-coding-practice': typeof PythonCodingPracticeRoute
  '/python-tutorial': typeof PythonTutorialRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sql-interview-questions': typeof SqlInterviewQuestionsRoute
  '/terms': typeof TermsRoute
  '/tutorial': typeof TutorialRoute
  '/python-tutorial/$topicId': typeof PythonTutorialTopicIdRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/c-cpp-coding-practice': typeof CCppCodingPracticeRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/cpp': typeof CppRoute
  '/engine': typeof EngineRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/gcp': typeof GcpRoute
  '/gcp-data-engineer-interview': typeof GcpDataEngineerInterviewRoute
  '/interview': typeof InterviewRoute
  '/java': typeof JavaRoute
  '/java-tutorial': typeof JavaTutorialRoute
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/pyspark': typeof PysparkRoute
  '/pyspark-practice': typeof PysparkPracticeRoute
  '/python': typeof PythonRoute
  '/python-coding-practice': typeof PythonCodingPracticeRoute
  '/python-tutorial': typeof PythonTutorialRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sql-interview-questions': typeof SqlInterviewQuestionsRoute
  '/terms': typeof TermsRoute
  '/tutorial': typeof TutorialRoute
  '/python-tutorial/$topicId': typeof PythonTutorialTopicIdRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/c-cpp-coding-practice': typeof CCppCodingPracticeRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/cpp': typeof CppRoute
  '/engine': typeof EngineRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/gcp': typeof GcpRoute
  '/gcp-data-engineer-interview': typeof GcpDataEngineerInterviewRoute
  '/interview': typeof InterviewRoute
  '/java': typeof JavaRoute
  '/java-tutorial': typeof JavaTutorialRoute
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/pyspark': typeof PysparkRoute
  '/pyspark-practice': typeof PysparkPracticeRoute
  '/python': typeof PythonRoute
  '/python-coding-practice': typeof PythonCodingPracticeRoute
  '/python-tutorial': typeof PythonTutorialRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sql-interview-questions': typeof SqlInterviewQuestionsRoute
  '/terms': typeof TermsRoute
  '/tutorial': typeof TutorialRoute
  '/python-tutorial/$topicId': typeof PythonTutorialTopicIdRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/c-cpp-coding-practice'
    | '/chat'
    | '/contact'
    | '/cpp'
    | '/engine'
    | '/faq'
    | '/feedback'
    | '/gcp'
    | '/gcp-data-engineer-interview'
    | '/interview'
    | '/java'
    | '/java-tutorial'
    | '/practice'
    | '/privacy'
    | '/pyspark'
    | '/pyspark-practice'
    | '/python'
    | '/python-coding-practice'
    | '/python-tutorial'
    | '/reset-password'
    | '/sitemap.xml'
    | '/sql-interview-questions'
    | '/terms'
    | '/tutorial'
    | '/python-tutorial/$topicId'
    | '/topic/$slug'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/c-cpp-coding-practice'
    | '/chat'
    | '/contact'
    | '/cpp'
    | '/engine'
    | '/faq'
    | '/feedback'
    | '/gcp'
    | '/gcp-data-engineer-interview'
    | '/interview'
    | '/java'
    | '/java-tutorial'
    | '/practice'
    | '/privacy'
    | '/pyspark'
    | '/pyspark-practice'
    | '/python'
    | '/python-coding-practice'
    | '/python-tutorial'
    | '/reset-password'
    | '/sitemap.xml'
    | '/sql-interview-questions'
    | '/terms'
    | '/tutorial'
    | '/python-tutorial/$topicId'
    | '/topic/$slug'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/c-cpp-coding-practice'
    | '/chat'
    | '/contact'
    | '/cpp'
    | '/engine'
    | '/faq'
    | '/feedback'
    | '/gcp'
    | '/gcp-data-engineer-interview'
    | '/interview'
    | '/java'
    | '/java-tutorial'
    | '/practice'
    | '/privacy'
    | '/pyspark'
    | '/pyspark-practice'
    | '/python'
    | '/python-coding-practice'
    | '/python-tutorial'
    | '/reset-password'
    | '/sitemap.xml'
    | '/sql-interview-questions'
    | '/terms'
    | '/tutorial'
    | '/python-tutorial/$topicId'
    | '/topic/$slug'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CCppCodingPracticeRoute: typeof CCppCodingPracticeRoute
  ChatRoute: typeof ChatRoute
  ContactRoute: typeof ContactRoute
  CppRoute: typeof CppRoute
  EngineRoute: typeof EngineRoute
  FaqRoute: typeof FaqRoute
  FeedbackRoute: typeof FeedbackRoute
  GcpRoute: typeof GcpRoute
  GcpDataEngineerInterviewRoute: typeof GcpDataEngineerInterviewRoute
  InterviewRoute: typeof InterviewRoute
  JavaRoute: typeof JavaRoute
  JavaTutorialRoute: typeof JavaTutorialRoute
  PracticeRoute: typeof PracticeRoute
  PrivacyRoute: typeof PrivacyRoute
  PysparkRoute: typeof PysparkRoute
  PysparkPracticeRoute: typeof PysparkPracticeRoute
  PythonRoute: typeof PythonRoute
  PythonCodingPracticeRoute: typeof PythonCodingPracticeRoute
  PythonTutorialRoute: typeof PythonTutorialRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SqlInterviewQuestionsRoute: typeof SqlInterviewQuestionsRoute
  TermsRoute: typeof TermsRoute
  TutorialRoute: typeof TutorialRoute
  TopicSlugRoute: typeof TopicSlugRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sql-interview-questions': {
      id: '/sql-interview-questions'
      path: '/sql-interview-questions'
      fullPath: '/sql-interview-questions'
      preLoaderRoute: typeof SqlInterviewQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/python-tutorial': {
      id: '/python-tutorial'
      path: '/python-tutorial'
      fullPath: '/python-tutorial'
      preLoaderRoute: typeof PythonTutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/python-coding-practice': {
      id: '/python-coding-practice'
      path: '/python-coding-practice'
      fullPath: '/python-coding-practice'
      preLoaderRoute: typeof PythonCodingPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/python': {
      id: '/python'
      path: '/python'
      fullPath: '/python'
      preLoaderRoute: typeof PythonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pyspark-practice': {
      id: '/pyspark-practice'
      path: '/pyspark-practice'
      fullPath: '/pyspark-practice'
      preLoaderRoute: typeof PysparkPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pyspark': {
      id: '/pyspark'
      path: '/pyspark'
      fullPath: '/pyspark'
      preLoaderRoute: typeof PysparkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/java-tutorial': {
      id: '/java-tutorial'
      path: '/java-tutorial'
      fullPath: '/java-tutorial'
      preLoaderRoute: typeof JavaTutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/java': {
      id: '/java'
      path: '/java'
      fullPath: '/java'
      preLoaderRoute: typeof JavaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gcp-data-engineer-interview': {
      id: '/gcp-data-engineer-interview'
      path: '/gcp-data-engineer-interview'
      fullPath: '/gcp-data-engineer-interview'
      preLoaderRoute: typeof GcpDataEngineerInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gcp': {
      id: '/gcp'
      path: '/gcp'
      fullPath: '/gcp'
      preLoaderRoute: typeof GcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine': {
      id: '/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof EngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpp': {
      id: '/cpp'
      path: '/cpp'
      fullPath: '/cpp'
      preLoaderRoute: typeof CppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c-cpp-coding-practice': {
      id: '/c-cpp-coding-practice'
      path: '/c-cpp-coding-practice'
      fullPath: '/c-cpp-coding-practice'
      preLoaderRoute: typeof CCppCodingPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/$slug': {
      id: '/topic/$slug'
      path: '/topic/$slug'
      fullPath: '/topic/$slug'
      preLoaderRoute: typeof TopicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/python-tutorial/$topicId': {
      id: '/python-tutorial/$topicId'
      path: '/$topicId'
      fullPath: '/python-tutorial/$topicId'
      preLoaderRoute: typeof PythonTutorialTopicIdRouteImport
      parentRoute: typeof PythonTutorialRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PythonTutorialRouteChildren {
  PythonTutorialTopicIdRoute: typeof PythonTutorialTopicIdRoute
}

const PythonTutorialRouteChildren: PythonTutorialRouteChildren = {
  PythonTutorialTopicIdRoute: PythonTutorialTopicIdRoute,
}

const PythonTutorialRouteWithChildren = PythonTutorialRoute._addFileChildren(
  PythonTutorialRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CCppCodingPracticeRoute: CCppCodingPracticeRoute,
  ChatRoute: ChatRoute,
  ContactRoute: ContactRoute,
  CppRoute: CppRoute,
  EngineRoute: EngineRoute,
  FaqRoute: FaqRoute,
  FeedbackRoute: FeedbackRoute,
  GcpRoute: GcpRoute,
  GcpDataEngineerInterviewRoute: GcpDataEngineerInterviewRoute,
  InterviewRoute: InterviewRoute,
  JavaRoute: JavaRoute,
  JavaTutorialRoute: JavaTutorialRoute,
  PracticeRoute: PracticeRoute,
  PrivacyRoute: PrivacyRoute,
  PysparkRoute: PysparkRoute,
  PysparkPracticeRoute: PysparkPracticeRoute,
  PythonRoute: PythonRoute,
  PythonCodingPracticeRoute: PythonCodingPracticeRoute,
  PythonTutorialRoute: PythonTutorialRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SqlInterviewQuestionsRoute: SqlInterviewQuestionsRoute,
  TermsRoute: TermsRoute,
  TutorialRoute: TutorialRoute,
  TopicSlugRoute: TopicSlugRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
